# Site settings
title: "Postershaala - AI-Powered Content Creation"
description: "AI-powered poster and content creation platform for politics, business, festivals, and branding."
url: "https://postershaala.com"   # your custom domain
baseurl: ""                       # empty since you’re using a custom domain (important!)

# Repository details (for GitHub metadata plugin)
repository: "aloklight/aloklight.github.io"

# Logo configuration
logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/postershaala-logo-black.png"
  desktop_height: "32px"
  desktop_width: "120px"

# Homepage settings
home: 
  limit_services: 6

# Collections
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

# Sass settings
sass:
  style: compressed # possible values: nested expanded compact compressed

# Plugins (GitHub Pages supports only whitelisted plugins)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata


# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - CNAME
  - .DS_Store